### ISSUE TITLE
Indicate range requests are supported.

### ISSUE THREAD

**Issue by ghost** [ErikNoren/WebApi.ProgressiveDownloads#1]
IE10, IE11 and probably Edge will only do range requests if the Accept-Ranges response headers contains "bytes". Firefox and Chrome will do a range request anyway.

So, in order to support all browsers, insert the "Accept-Ranges: bytes" response header when the ProgressiveDownload class is used.

Will create a pull request.

**Comment by ErikNoren** [comment]
Pull request was accepted and a new NuGet package was created and published to the NuGet repository. I'll consider the issue closed if you confirm it's working as expected.

**Comment by ghost** [comment]
Thanks for the quick update. I'll check Monday and let you know. Merry Christmas!

**Comment by ghost** [comment]
This works entirely as expected, thanks.

**Comment by ErikNoren** [comment]
Thanks again for the pull request and validating!
